/**
 * Fox & Hound API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModelsCandidateRatingDTO { 
    category?: string;
    orderId?: number;
    question?: string;
    ratingCandidate?: number;
    ratingCardId?: number;
    textResponseCandidate?: string;
    timeStampCandidate?: string;
    userEmail?: string;
}

