/**
 * Fox & Hound API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelsCategoryEnum } from './modelsCategoryEnum';


export interface ModelsManagementSummaryRatingDTO { 
    category?: ModelsCategoryEnum;
    rating?: number;
}
export namespace ModelsManagementSummaryRatingDTO {
}


