/**
 * Fox & Hound API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModelsAverageRatingDTO { 
    NumberOfAgreedRatings?: number;
    average?: number;
    ratingCardId?: number;
}

