/**
 * Fox & Hound API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModelsHeadDataDTO { 
    'abstract'?: string;
    age?: number;
    agreedOn?: boolean;
    experienceSince?: string;
    name?: string;
    startAtProdyna?: string;
    userEmail?: string;
}

