/**
 * Fox & Hound API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ModelsEmployerRatingDTO { 
    category?: string;
    notApplicableCandidate?: boolean;
    notApplicableEmployer?: boolean;
    orderId?: number;
    question?: string;
    ratingCandidate?: number;
    ratingCardId?: number;
    ratingEmployer?: number;
    textResponseCandidate?: string;
    textResponseEmployer?: string;
    timeStampCandidate?: string;
    timeStampEmployer?: string;
    userEmail?: string;
}

