/**
 * Fox & Hound API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// TODO: we should check if we have the header data out of this dto (i think they will only be used once)
export interface ModelsEmployerRatingDTO {
    category?: string;
    orderId?: number;
    question?: string;
    ratingCandidate?: number;
    ratingCardId?: number;
    ratingEmployer?: number;
    agreedOn?: number; // TODO: include in BE
    name?: string;
    abstract?: string;
    experienceSince?: Date;
    startAtProdyna?: Date;
    age?: number;
    notApplicableCandidate?: boolean; // TODO: include those in the BE
    notApplicableEmployer?: boolean; // TODO: include those in the BE
    textResponseCandidate?: string;
    textResponseEmployer?: string;
    timeStampCandidate?: string;
    timeStampEmployer?: string;
    userEmail?: string;
}

