/**
 * Fox & Hound API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ModelsCategoryEnum = 'Performance' | 'Technical Skillset' | 'Technical Predispositions' | 'Sales' | 'Recruiting' | 'Teamwork' | 'Coaching' | 'Prodyna Insights' | 'Overall';

export const ModelsCategoryEnum = {
    CategoryPerformance: 'Performance' as ModelsCategoryEnum,
    CategoryTechnicalSkillset: 'Technical Skillset' as ModelsCategoryEnum,
    CategoryTechnicalPredisposition: 'Technical Predispositions' as ModelsCategoryEnum,
    CategorySales: 'Sales' as ModelsCategoryEnum,
    CategoryRecruiting: 'Recruiting' as ModelsCategoryEnum,
    CategoryTeamwork: 'Teamwork' as ModelsCategoryEnum,
    CategoryCoaching: 'Coaching' as ModelsCategoryEnum,
    CategoryProdynaInsights: 'Prodyna Insights' as ModelsCategoryEnum,
    CategoryOverall: 'Overall' as ModelsCategoryEnum
};

