/**
 * Fox & Hound API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelsManagementSummaryRatingDTO } from './modelsManagementSummaryRatingDTO';


export interface ModelsManagementSummaryDTO { 
    /**
     * Array of management ratings
     */
    ratings?: Array<ModelsManagementSummaryRatingDTO>;
    userEmail?: string;
}

