basePath: /api
definitions:
  models.CandidateRatingDTO:
    properties:
      category:
        type: string
      orderId:
        type: integer
      question:
        type: string
      ratingCandidate:
        type: integer
      ratingCardId:
        type: integer
      textResponseCandidate:
        type: string
      timeStampCandidate:
        type: string
      userEmail:
        type: string
    type: object
  models.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  models.RatingCard:
    properties:
      category:
        type: string
      id:
        type: integer
      orderId:
        type: integer
      question:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a Gin-based API for the Fox & Hound application.
  title: Fox & Hound API
  version: "1.0"
paths:
  /rating-cards:
    get:
      description: Retrieves all rating cards from the database
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.RatingCard'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get all rating cards
      tags:
      - rating
  /ratings/candidate:
    get:
      description: Fetches rating cards and enriches them with existing ratings for
        a given user
      parameters:
      - description: User Email
        in: query
        name: userEmail
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CandidateRatingDTO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ErrorResponse'
      summary: Get candidate ratings
      tags:
      - rating
swagger: "2.0"
